### PR TITLE
Change the absolute path to an easy-to-use relative path

### PR DESCRIPTION
**Pull request by hdcola**
If this is not changed, `swift build` command  will not work properly.

### CODE REVIEW

**Comment by cipi1965** [comment]
We should remove these files completely, can you please update pr?

**Comment by hdcola** [comment]
> We should remove these files completely, can you please update pr?

Do you want to delete these examples, or do you want to delete these three Package.resolved files?

**Comment by zmeyc** [comment]
*.resolved files were added by mistake, they need to be deleted. They will be regenerated on first build.

**Comment by cipi1965** [comment]
> > We should remove these files completely, can you please update pr?
> 
> Do you want to delete these examples, or do you want to delete these three Package.resolved files?

Just delete Package.resolved in all examples

**Comment by cipi1965** [comment]
Thank you, merging as soon as actions finish up

**Pull request merged**
